### ISSUE TITLE
Auto-clean for transmission

### ISSUE THREAD

**Issue by scoony** [scoony/conky-nas#8]
Add a feature to clean the transmission list (remove completed)

**Comment by Z0uZOU** [comment]
Variable added : 
transmission_autoclean=""
transmission_clean_unregistered=""
transmission_clean_finished=""
transmission_autoclean : clean all finished and unregistered torrents
transmission_clean_unregistered : clean only all unregistered torrents
transmission_clean_finished : clean only all finished torrents
